version: '3'

services:
  mariadb-test:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=pesat_test
    ports:
      - '3307:3306'

networks:
  default:
    name: backend_test
